# ML-Zoomcamp: introduction to Numpy

In [2]:
import numpy as np

### Matrices

In [ ]:
np.zeros(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,2.5) #crea un array de 10 elementos con el valor 2.5

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [4]:
A=np.array([1,4,8,12,2,2])

In [5]:
A[2] #acceder al tercer elemento del array A

np.int64(8)

In [6]:
A[2]=10 # modificar el tercer elemento del array A

In [8]:
np.arange(3, 10) #crea un array con valores del 3 al 9

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,1,11) #crea un array con 11 valores equidistantes entre 0 y 1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [10]:
np.zeros((3,4)) #crea un array de 3 filas y 4 columnas con ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
N=np.array([[1,2,3],
[4,5,6],
[7,8,9]]) #crea un array de 3 filas y 3

In [14]:
N[0,1] #acceder al elemento de la primera fila y segunda columna

np.int64(2)

In [15]:
N[0,1]=4 #modificar el elemento de la primera fila y segunda columna

In [16]:
N

array([[1, 4, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
N[2]=[4,6,1] #modificar la tercera fila del array N

In [18]:
N

array([[1, 4, 3],
       [4, 5, 6],
       [4, 6, 1]])

In [19]:
N[:,1] #acceder a la segunda columna del array N

array([4, 5, 6])

In [ ]:
np.random.seed(2) #establece la semilla para generar números aleatorios
np.random.rand(5,2) # crea un array de 5 filas y 2 columnas con valores aleatorios entre 0 y 1 y con distribución uniforme

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [22]:
np.random.seed(2) #establece la semilla para generar números aleatorios
np.random.randn(5,2) # crea un array de 5 filas y 2 columnas con valores aleatorios entre 0 y 1 y con distribución normal

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [23]:
np.random.seed(2) #establece la semilla para generar números aleatorios
100*np.random.randn(5,2) # crea un array de 5 filas y 2 columnas con valores aleatorios entre 0 y 1 y con distribución normal

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [25]:
np.random.seed(2) #establece la semilla para generar números aleatorios
np.random.randint(low=1, high=100, size=(5,2)) # crea un array de 5 filas y 2 columnas con valores aleatorios enteros entre 1 y 10

array([[41, 16],
       [73, 23],
       [44, 83],
       [76,  8],
       [35, 50]], dtype=int32)

### Element-wise operations

In [27]:
a=np.arange(5) #crea un array con valores del 0 al 4
a

array([0, 1, 2, 3, 4])

In [31]:
b=(10+(a*2))**2/100 #crea un array con valores del 0 al 4, los multiplica por 2, le suma 10, eleva al cuadrado y divide entre 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [32]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

### Operaciones de comparación

In [34]:
a>=1 # compara cada elemento del array a con el valor 1 y devuelve un array de booleanos

array([False,  True,  True,  True,  True])

In [35]:
a>b

array([False, False,  True,  True,  True])

In [36]:
a[a>b] # devuelve un array con los elementos de a que son mayores que los elementos de b

array([2, 3, 4])

### Operaciones de resumen

In [37]:
a.min()

np.int64(0)

In [38]:
a.max()

np.int64(4)

In [39]:
a.mean()

np.float64(2.0)

In [40]:
a.std()

np.float64(1.4142135623730951)