# Algebra matricial

In [1]:
import numpy as np

## operaciones con vectores

In [2]:
u=np.array([1,2,3])
v=np.array([4,5,6])

In [3]:
u+v

array([5, 7, 9])

In [5]:
2*v

array([ 8, 10, 12])

#### multiplicación

In [7]:
def vec_vec_mult(u,v):
    assert u.shape[0] == v.shape[0] # ver si los vectores tienen la misma dimension
    n=u.shape[0] # obtener la longitud de los vectores
    result = 0.0 # inicializar el resultado
    for i in range(n):
        result=result+u[i]*v[i] # multiplicar los elementos correspondientes y sumarlos
    return result

In [8]:
 vec_vec_mult(u,v)

np.float64(32.0)

In [9]:
u.dot(v)

np.int64(32)

In [10]:
U=np.array([[1,2,3],[4,5,6]])

In [11]:
U

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
def mat_vex_mult(U,v):
    assert U.shape[1] == v.shape[0] # ver si la segunda dimension de U (columnas) es igual a la primera dimension de v (filas)
    num_rows=U.shape[0] # obtener el numero de filas de U
    result=np.zeros(num_rows) # inicializar el resultado
    for i in range(num_rows):
        result[i]=vec_vec_mult(U[i],v) # multiplicar la fila i de U con el vector v
    return result

In [13]:
mat_vex_mult(U,v)

array([32., 77.])

In [14]:
U.dot(v)

array([32, 77])

In [15]:
V=np.array([[1,2],[3,4],[5,6]])

In [ ]:
def mat_mat_mult(U,V):
    assert U.shape[1] == V.shape[0] # ver si la segunda dimension de U (columnas) es igual a la primera dimension de V (filas)
    num_rows=U.shape[0] # obtener el numero de filas de U
    num_cols=V.shape[1] # obtener el numero de columnas de V
    result=np.zeros((num_rows,num_cols)) # inicializar el resultado
    for i in range(num_cols):
        vi=V[:,i] # obtener la columna i de V
        Uvi=mat_vex_mult(U,vi) # multiplicar U con la columna i de V
        result[:,i]=Uvi # asignar el resultado a la columna i de result
    return result

In [17]:
mat_mat_mult(U,V)

array([[22., 28.],
       [49., 64.]])

In [18]:
U.dot(V)

array([[22, 28],
       [49, 64]])

#### matriz identidad

In [23]:
I=np.eye(2)

In [24]:
V.dot(I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [38]:
Vs=V[[1,2]] # seleccionar las filas 1 y 2 de V 
Vs

array([[3, 4],
       [5, 6]])

In [41]:
Vs_inv=np.linalg.inv(Vs)
Vs_inv

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [42]:
Vs_inv.dot(Vs)

array([[ 1.00000000e+00,  8.88178420e-16],
       [-1.55431223e-15,  1.00000000e+00]])