In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl_
import seaborn as sbn

In [2]:
pd.__version__

'2.3.2'

In [3]:
car=pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
car

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551


In [4]:
car["fuel_type"].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [5]:
car.isna().sum() # Count of missing values in each column

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [6]:
car.loc[car['origin']=='Asia','fuel_efficiency_mpg'].max() # Maximum fuel efficiency for Asian cars

np.float64(23.759122836520497)

In [7]:
car['horsepower'].median()

np.float64(149.0)

In [8]:
car['horsepower'].mode() # Most common horsepower value

0    152.0
Name: horsepower, dtype: float64

In [9]:
car['horsepower'].fillna(car['horsepower'].mode()[0]) # Fill missing horsepower values with the mode. [0] is used to get the first value from the mode series.

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [10]:
car['horsepower'].median()

np.float64(149.0)

In [15]:
X=np.array(car.loc[car['origin']=='Asia',['vehicle_weight','model_year']].head(7))
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [19]:
XT=X.T
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 , 2659.43145076,
        2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        , 2016.        ,
        2014.        , 2019.        ]])

In [21]:
XTX=XT.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [ ]:
Y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
Y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [28]:
XTX_inv=np.linalg.inv(XTX)
XTX_XT=XTX_inv.dot(XT)
w=np.round(XTX_XT.dot(Y),2)
w

array([0.01, 0.5 ])